apiVersion: v1
kind: ConfigMap
metadata:
    name: runner-pod-npu-scheduler-config
    namespace: kube-system
data:
    scheduler-config.yaml: |
        apiVersion: kubescheduler.config.k8s.io/v1
        kind: KubeSchedulerConfiguration
        leaderElection:
          leaderElect: false
          resourceNamespace: kube-system
          resourceName: runner-pod-npu-scheduler
        profiles:
          - schedulerName: runner-pod-npu-scheduler
            plugins:
              filter:
                enabled:
                  - name: runnerScheduler
